using Geophysics, Test

st = Standard(0)
@test gravity() == gravity(0)
@test temperature() == temperature(Standard(0))
@test pressure() == pressure(st)
@test density() ≈ density(st)
@test thermalconductivity() == thermalconductivity(st)
@test elasticity() == elasticity(st)
@test viscosity() == viscosity(st)
@test specificvolume() ≈ specificvolume(st)
@test specificenergy() == specificenergy(st)
@test specificenthalpy() == specificenthalpy(st)
@test heatcapacity() ≈ heatcapacity(st)
@test thermaldiffusivity() ≈ thermaldiffusivity(st)
@test prandtl() ≈ prandtl(st)
@test sonicspeed() == sonicspeed(st)
@test impedance() ≈ impedance(st)
