name = "Geophysics"
uuid = "74efdf00-b554-44e1-bd21-abb9281d951c"
authors = ["Michael Reed"]
version = "0.3.5"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
AbstractTensors = "a8e43f4a-99b7-5565-8bf1-0165161caaea"
UnitSystems = "3a241a3c-2137-41aa-af5e-1388e404ca09"

[compat]
julia = "1"
AbstractTensors = "0.7"
UnitSystems = "0.3.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
